# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simtoonia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Simtoonia

pod 'MessageKit'
pod 'Scaledrone', '~> 0.3.0'
end
